version: '3.4'

services:

  kafka:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
     # - "./test/123.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro"
     # - "./test/123.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro"
     # - "./test/123.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro"
      - "./cert/kafka.server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "./cert/kafka.server.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=172.20.21.84:2181,172.20.21.222:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=password
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://172.20.21.232:9093,CLIENT://172.20.21.232:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CERTIFICATE_PASSWORD=qwerty
      - KAFKA_TLS_TYPE=JKS
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password

volumes:
  kafka_data:
    driver: local


